#%RAML 1.0 DocumentationItem
title: Authentication
content: |
  Most of the API requests require authentication. This is done via a
  _request header_ named `Authorization:` containing an **access token**, which
  has to be send along with every request.
  To obtain an access token, the following steps have to be performed:
  1. Create an **account** via the `/create` resource.
  2. Create an **access token** via the `/auth` resource using the credentials
     (login/password) returned in step 1.
  3. Provide the **access token** returned in step 2 as the value of the
     `Authorization` header in every following request.
