#%RAML 1.0 DocumentationItem
title: Home
content: |
 Welcome to the _LightningHub API_ Documentation. The _LightningHub API_
 allows you to connect your Bitcoin/Lightning [Bluewallet App](https://bluewallet.io) and serve
 multiple user accounts via a shared Lightning Node.
